def doInit():
    music.set_volume(23)
    music.set_tempo(70)

def on_button_pressed_a():
    basic.show_leds("""
        . . # . .
        . . # . .
        . # . # .
        . # # # .
        # . . . #
        """)
    doInit()
    music.play_tone(523, music.beat(BeatFraction.QUARTER))
    music.play_tone(494, music.beat(BeatFraction.QUARTER))
    music.play_tone(523, music.beat(BeatFraction.WHOLE))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
    music.play_tone(494, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(440, music.beat(BeatFraction.QUARTER))
    music.play_tone(392, music.beat(BeatFraction.QUARTER))
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    music.play_tone(523, music.beat(BeatFraction.WHOLE))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.play_tone(659, music.beat(BeatFraction.QUARTER))
    music.play_tone(698, music.beat(BeatFraction.WHOLE))
    music.play_tone(880, music.beat(BeatFraction.WHOLE))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(587, music.beat(BeatFraction.QUARTER))
    music.play_tone(523, music.beat(BeatFraction.QUARTER))
    music.play_tone(587, music.beat(BeatFraction.WHOLE))
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
input.on_button_pressed(Button.A, on_button_pressed_a)

def doSound_B2():
    music.rest(music.beat(BeatFraction.WHOLE))
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    music.play_tone(415, music.beat(BeatFraction.HALF))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(494, music.beat(BeatFraction.HALF))
    music.play_tone(330, music.beat(BeatFraction.HALF))
    music.play_tone(659, music.beat(BeatFraction.BREVE))
    music.rest(music.beat(BeatFraction.WHOLE))

def on_gesture_shake():
    basic.show_icon(IconNames.HEART)
input.on_gesture(Gesture.SHAKE, on_gesture_shake)

def on_button_pressed_b():
    doInit()
    doSound_B1()
    music.play_tone(523, music.beat(BeatFraction.DOUBLE))
    music.rest(music.beat(BeatFraction.QUARTER))
    doSound_B2()
    doSound_B1()
    music.play_tone(523, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.HALF))
    doSound_B3()
input.on_button_pressed(Button.B, on_button_pressed_b)

def doSound_B3():
    music.play_tone(523, music.beat(BeatFraction.QUARTER))
    music.play_tone(587, music.beat(BeatFraction.QUARTER))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(523, music.beat(BeatFraction.QUARTER))
    music.play_tone(587, music.beat(BeatFraction.QUARTER))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(523, music.beat(BeatFraction.QUARTER))
    music.play_tone(587, music.beat(BeatFraction.QUARTER))
    music.play_tone(659, music.beat(BeatFraction.DOUBLE))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(494, music.beat(BeatFraction.HALF))
    music.play_tone(523, music.beat(BeatFraction.HALF))
    music.play_tone(659, music.beat(BeatFraction.DOUBLE))
    music.rest(music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(698, music.beat(BeatFraction.QUARTER))
    music.play_tone(587, music.beat(BeatFraction.DOUBLE))
    music.rest(music.beat(BeatFraction.QUARTER))
    music.rest(music.beat(BeatFraction.WHOLE))
def doSound_B1():
    music.play_tone(440, music.beat(BeatFraction.WHOLE))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(440, music.beat(BeatFraction.HALF))
    music.play_tone(523, music.beat(BeatFraction.HALF))
    music.play_tone(587, music.beat(BeatFraction.HALF))
    music.play_tone(392, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.HALF))
    music.play_tone(587, music.beat(BeatFraction.QUARTER))