music.play_tone(523, music.beat(BeatFraction.QUARTER))
music.play_tone(494, music.beat(BeatFraction.QUARTER))
music.play_tone(523, music.beat(BeatFraction.WHOLE))
music.play_tone(659, music.beat(BeatFraction.WHOLE))
music.play_tone(494, music.beat(BeatFraction.WHOLE))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(440, music.beat(BeatFraction.QUARTER))
music.play_tone(392, music.beat(BeatFraction.QUARTER))